"""initial schema — full Skill Builder table set

Baseline migration: creates every table from the SQLAlchemy metadata
(source_documents, document_sections, policy_clauses, candidate_rules,
approved_policy_rules, skill_versions, extraction_runs, document_profiles,
policy_atoms, unresolved_items, review_events). Subsequent migrations should be
authored/autogenerated against this baseline.

Revision ID: 0001_initial
Revises:
Create Date: 2026-06-14
"""
from alembic import op

from skillbuilder.db import Base

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    Base.metadata.create_all(op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(op.get_bind())
